[tools]
nodejs = '26.4.0'
python = '3.14.6'
awscli = '2.35.11'
go = "1.26.4"
terraform = '1.15.7'
rust="1.96.0"
direnv="2.37.1"
usage = "latest"
aws-sam-cli="1.135.0"
lazydocker="latest"
pnpm = "11.9.0"
jq = "latest"
yq = "latest"
