[[plugins]]
repo = 'editorconfig/editorconfig-vim'

#[[plugins]]
#repo = 'tpope/vim-surround'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/plugins/vim-gitgutter.vim
'''

[[plugins]]
repo = 'andys8/vim-elm-syntax'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'

#[[plugins]]
#repo = 'mg979/vim-visual-multi'

[[plugins]]
repo = 'myusuf3/numbers.vim'
hook_add = '''
source ~/.config/nvim/plugins/numbers.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline-themes.vim
'''

[[plugins]]
repo = 'rafi/awesome-vim-colorschemes'

#[[plugins]]
#repo = 'othree/yajs.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
source ~/.config/nvim/plugins/vim-table-mode.vim
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'MattesGroeger/vim-bookmarks'
hook_add = '''
source ~/.config/nvim/plugins/vim-bookmarks.vim
'''

#  [[plugins]]
#  repo = 'prettier/vim-prettier'
#  build = 'yarn install --frozen-lockfile --production'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  let g:highlightedyank_highlight_duration = 150
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  let g:neoterm_autoinsert = 1
  let g:neoterm_autoscroll = 1
  nnoremap <leader>tl :<c-u>exec v:count.'Tclear'<cr>
'''

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
source ~/.config/nvim/plugins/fern.vim
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fern-preview.vim
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown','pandoc.markdown','rmd']
build = 'sh -c "cd app && yarn install"'
hooks_add = '''
  source ~/.config/nvim/plugins/markdown-preview.vim
'''

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
hook_add = '''
source ~/.config/nvim/plugins/vim-css3-syntax.vim
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
hook_add = '''
source ~/.config/nvim/plugins/vim-jsx-typescript.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  source ~/.config/nvim/plugins/fzf.vim
'''

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/remote'
merged = 0
hook_add = '''
  source ~/.config/nvim/plugins/fzf-preview.vim
'''

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  source ~/.config/nvim/plugins/vim-indent-guides.vim
'''

[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'puremourning/vimspector'
hook_add = '''
  source ~/.config/nvim/plugins/vimspector.vim
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'
hook_add = '''
  source ~/.config/nvim/plugins/tcomment_vim.vim
'''

[[plugins]]
repo = 'ziglang/zig.vim'
