[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_add = '''
source ~/.config/nvim/plugins/vim-prettier.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'mg979/vim-visual-multi'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
    let g:deoplete#sources#jedi#python_path = '/Users/kurage/.asdf/shims/python3.8'
'''

[[plugins]]
repo = 'myusuf3/numbers.vim'
hook_add = '''
source ~/.config/nvim/plugins/numbers.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline-themes.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
source ~/.config/nvim/plugins/vim-devicons.vim
'''

[[plugins]]
repo = 'rafi/awesome-vim-colorschemes'

[[plugins]]
repo = 'shougo/deol.nvim'
hook_add = '''
source ~/.config/nvim/plugins/deol.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons' 
hook_add = '''
source ~/.config/nvim/plugins/defx-icons.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'
hook_add = '''
source ~/.config/nvim/plugins/defx-git.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons','defx-git']
hook_add = '''
source ~/.config/nvim/plugins/defx.vim
'''

[[plugins]]
repo = 'othree/html5.vim'
hook_add = '''
source ~/.config/nvim/plugins/html5.vim
'''

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
hook_add = '''
source ~/.config/nvim/plugins/vim-css3-syntax.vim
'''

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
source ~/.config/nvim/plugins/emmet.vim
'''

[[plugins]]
repo = 'othree/yajs.vim'
