[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'bfredl/nvim-miniyank'
hook_add = '''
source ~/.config/nvim/plugins/miniyank.vim
'''

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
source ~/.config/nvim/plugins/undotree.vim
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/plugins/vim-gitgutter.vim
'''

[[plugins]]
repo = 'andys8/vim-elm-syntax'

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
source ~/.config/nvim/plugins/nerdtree.vim
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'mg979/vim-visual-multi'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
    let g:deoplete#sources#jedi#python_path = '/Users/kurage/.asdf/shims/python3.8'
'''

[[plugins]]
repo = 'myusuf3/numbers.vim'
hook_add = '''
source ~/.config/nvim/plugins/numbers.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline-themes.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
source ~/.config/nvim/plugins/vim-devicons.vim
'''

[[plugins]]
repo = 'rafi/awesome-vim-colorschemes'

[[plugins]]
repo = 'shougo/deol.nvim'
hook_add = '''
source ~/.config/nvim/plugins/deol.vim
'''

[[plugins]]
repo = 'othree/html5.vim'
hook_add = '''
source ~/.config/nvim/plugins/html5.vim
'''

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
hook_add = '''
source ~/.config/nvim/plugins/vim-css3-syntax.vim
'''

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
source ~/.config/nvim/plugins/emmet.vim
'''

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = '''
source ~/.config/nvim/plugins/vim-terraform.vim
'''

[[plugins]]
repo = 'nikvdp/ejs-syntax'
hook_add = '''
source ~/.config/nvim/plugins/ejs-syntax.vim
'''

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
hook_add = '''
source ~/.config/nvim/plugins/preview-markdown.vim
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
source ~/.config/nvim/plugins/vim-table-mode.vim
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
hook_add = '''
source ~/.config/nvim/plugins/vim-jsx-typescript.vim
'''

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'APZelos/blamer.nvim'
rev =  "v1.2.0"
hook_add = '''
source ~/.config/nvim/plugins/blamer.vim
'''

[[plugins]]
repo = 'MattesGroeger/vim-bookmarks'
hook_add = '''
source ~/.config/nvim/plugins/vim-bookmarks.vim
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
source ~/.config/nvim/plugins/vim-easymotion.vim
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  let g:highlightedyank_highlight_duration = 150
'''

[[plugins]]
repo = 'skanehira/translate.vim'
hook_add = '''
  source ~/.config/nvim/plugins/translate.vim
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  let g:neoterm_autoinsert = 1
  let g:neoterm_autoscroll = 1
  nnoremap <leader>tl :<c-u>exec v:count.'Tclear'<cr>
'''
